server:
  port: 8080

spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oomall4?serverTimezone=UTC
    username: hsx
    password: hsx
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #  最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:7878/eureka/


mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.freight.domain
  #mapper。xml所在的位置
  mapper-locations: classpath:com.xmu.freight.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

#redis配置
redis:
  #redis服务器主机
  host: localhost
  #登录密码
  password: ""
  #端口
  port: 6379
  #是否启用SSL支持
  ssl: flase
  jedis:
    pool:
      #给定时间内可分配的最大连接数，负值无限制
      max-active: 8
      #"空闲"连接最大,负值无限制
      max-idle: 8
      max-wait: 5000ms
      min-idle: 0